name: npm-publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter` and for Changelog
          fetch-depth: 0

      - name: standard fix
        run: yarn standard

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: true

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          # from-tag: 'current tag'
          to-tag: HEAD
          allow-unknown: true

      - name: 🛎️ Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.package-version.outputs.current-version}}
          # draft: true
          body: |
            ${{ steps.Changelog.outputs.changelog }}
